/**
 * ビジネスロジック固有のエラーコード
 * 既存サービス（app, auth, dev_tools, notification）用の統一コード体系
 */

// ===== 認証系エラー =====
export enum AuthErrorCode {
  INVALID_TOKEN = "ERR_AUTH_001",
  TOKEN_EXPIRED = "ERR_AUTH_002",
  REFRESH_TOKEN_INVALID = "ERR_AUTH_003",
  SESSION_EXPIRED = "ERR_AUTH_004",
  INVALID_CREDENTIALS = "ERR_AUTH_005",
  ACCOUNT_LOCKED = "ERR_AUTH_006",
  IP_BLOCKED = "ERR_AUTH_007",
  SUSPICIOUS_ACTIVITY = "ERR_AUTH_008",
}

// ===== ユーザー系エラー =====
export enum UserErrorCode {
  EMAIL_ALREADY_EXISTS = "ERR_USER_001",
  INVALID_EMAIL_FORMAT = "ERR_USER_002",
  WEAK_PASSWORD = "ERR_USER_003",
  ACCOUNT_SUSPENDED = "ERR_USER_004",
  USER_NOT_FOUND = "ERR_USER_005",
  INVALID_USER_DATA = "ERR_USER_006",
  PERMISSION_INSUFFICIENT = "ERR_USER_007",
}

// ===== 通知系エラー =====
export enum NotificationErrorCode {
  DELIVERY_FAILED = "ERR_NOTIFICATION_001",
  INVALID_RECIPIENT = "ERR_NOTIFICATION_002",
  TEMPLATE_NOT_FOUND = "ERR_NOTIFICATION_003",
  RATE_LIMIT_EXCEEDED = "ERR_NOTIFICATION_004",
  CHANNEL_UNAVAILABLE = "ERR_NOTIFICATION_005",
}

// ===== 開発ツール系エラー =====
export enum DevToolsErrorCode {
  UNAUTHORIZED_ACCESS = "ERR_DEVTOOLS_001",
  INVALID_OPERATION = "ERR_DEVTOOLS_002",
  RESOURCE_LOCKED = "ERR_DEVTOOLS_003",
  AUDIT_LOG_FAILED = "ERR_DEVTOOLS_004",
  STORAGE_OPERATION_FAILED = "ERR_DEVTOOLS_005",
}

// ===== バリデーション系エラー =====
export enum ValidationErrorCode {
  INVALID_INPUT = "ERR_VALIDATION_001",
  REQUIRED_FIELD_MISSING = "ERR_VALIDATION_002",
  FORMAT_ERROR = "ERR_VALIDATION_003",
  OUT_OF_RANGE = "ERR_VALIDATION_004",
}
